# 라이브러리 불러오기

In [84]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder   # 사이킷런 - 전처리 모듈 -> 레이블인코더, 원핫인코더

### 데이터 불러오기

In [85]:
csv_PATH = 'Clean_Dataset.csv'
df_origin = pd.read_csv(csv_PATH)

df_origin.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955


In [86]:
df_origin = df_origin.drop('Unnamed: 0', axis=1)    # 컬럼(Unnamed: 0) 삭제
df_origin.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955


### 레이블 인코딩
- 범주형 데이터(문자열 데이터)에 숫자를 순서대로 매기는 방식
- 판다스와 사이킷런 모두 활용 가능

### 판다스에서 레이블 인코딩하기 - pd.factorize()

In [87]:
df= df_origin.copy()    # 데이터프레임 복사
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   airline           300153 non-null  str    
 1   flight            300153 non-null  str    
 2   source_city       300153 non-null  str    
 3   departure_time    300153 non-null  str    
 4   stops             300153 non-null  str    
 5   arrival_time      300153 non-null  str    
 6   destination_city  300153 non-null  str    
 7   class             300153 non-null  str    
 8   duration          300153 non-null  float64
 9   days_left         300153 non-null  int64  
 10  price             300153 non-null  int64  
dtypes: float64(1), int64(2), str(8)
memory usage: 40.6 MB


In [88]:
df['airline'].value_counts()

airline
Vistara      127859
Air_India     80892
Indigo        43120
GO_FIRST      23173
AirAsia       16098
SpiceJet       9011
Name: count, dtype: int64

In [89]:
pd.factorize(df['airline'])[0]

array([0, 0, 1, ..., 2, 2, 2], shape=(300153,))

In [90]:
df.shape    # 행 개수, 열 개수

(300153, 11)

### .reshape(-1,1)
- 1차원 배열을 (행 수, 1) 형태의 2차원으로 바꿔서 데이터프레임의 새 컬럼으로 대입하기 쉽게 한다

In [91]:
pd.factorize(df['airline'])[0].reshape(-1,1)    # 2차원

array([[0],
       [0],
       [1],
       ...,
       [2],
       [2],
       [2]], shape=(300153, 1))

In [92]:
df['label_encoding'] = pd.factorize(df['airline'])[0].reshape(-1,1)
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,label_encoding
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,0
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,0
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,1
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,2
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,2


### 사이킷런으로 레이블 인코딩하기 - LabelEncoder(알파벳 순서로)

### fit_transform()
- fit : 범주(문자열) 학습
- transform : 숫자 변환
- 학습하고 숫자변환을 한 번에 수행

In [93]:
le = LabelEncoder()
le.fit_transform(df['airline'])

array([4, 4, 0, ..., 5, 5, 5], shape=(300153,))

In [94]:
pd.set_option('display.max_columns', None)  # 컬롬이 많아도 잘리지 않고 다 보이게 설정

In [95]:
df['airline_Label_Encoder'] = le.fit_transform(df['airline'])

df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,label_encoding,airline_Label_Encoder
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,0,4
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,0,4
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,1,0
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,2,5
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,2,5


#### 레이블 인코딩 역변환(디코딩)하기 - .inverse_transform()

In [96]:
le.inverse_transform(df['airline_Label_Encoder'])

df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,label_encoding,airline_Label_Encoder
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,0,4
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,0,4
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,1,0
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,2,5
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,2,5


### 원 핫 인코딩
- 레이블 인코딩 시 문제점이 의도치 않게 숫자 크기 정보가 생겨서 이를 크기 순서로 오해할 경우가 있다.
- 이 문제를 해결하기 위해 원핫 인코딩이 등장
- 각 범주(문자열)를 독립된 0 또는 1 컬럼으로 분리한다.
- 범주 개수가 많아지면 컬럼 수가 급증하는 트레이드오프가 있다.
- 범주 개수가 적으면 원핫 인코딩을 추천, 많을 떄는 신중히 판단을 한다.

### 판다스에서 원핫 인코딩하기 - pd.get_dummies()

In [97]:
df = df_origin.copy()

In [98]:
# class 컬럼을 원핫 인코딩
pd.get_dummies(df['class'])

,Business,Economy
0,False,True
1,False,True
2,False,True
3,False,True
4,False,True
...,...,...
300148,True,False
300149,True,False
300150,True,False
300151,True,False


In [ ]:
df = pd.get_dummies(df['class'])   # 'class 속성만 원핫 인코딩'
df.head()

,Business,Economy
0,False,True
1,False,True
2,False,True
3,False,True
4,False,True


In [100]:
df2 = df_origin.copy()

In [101]:
df2 = pd.get_dummies(df2)   # df2라는 데이터프레임 전체(범주형 컬럼 다 해당) 원핫 인코딩
df2.head()

duration  days_left  price  airline_AirAsia  airline_Air_India  \
0      2.17          1   5953            False              False   
1      2.33          1   5953            False              False   
2      2.17          1   5956             True              False   
3      2.25          1   5955            False              False   
4      2.33          1   5955            False              False   

   airline_GO_FIRST  airline_Indigo  airline_SpiceJet  airline_Vistara  \
0             False           False              True            False   
1             False           False              True            False   
2             False           False             False            False   
3             False           False             False             True   
4             False           False             False             True   

   flight_6E-102  flight_6E-105  flight_6E-113  flight_6E-121  flight_6E-123  \
0          False          False          False          False          False   
1          False          False          False          False          False   
2          False          False          False          False          False   
3          False          False          False          False          False   
4          False          False          False          False          False   

   flight_6E-126  flight_6E-128  flight_6E-131  flight_6E-132  flight_6E-134  \
0          False          False          False          False          False   
1          False          False          False          False          False   
2          False          False          False          False          False   
3          False          False          False          False          False   
4          False          False          False          False          False   

   flight_6E-135  flight_6E-136  flight_6E-138  flight_6E-139  flight_6E-146  \
0          False          False          False          False          False   
1          False          False          False          False          False   
2          False          False          False          False          False   
3          False          False          False          False          False   
4          False          False          False          False          False   

   flight_6E-148  flight_6E-149  flight_6E-151  flight_6E-152  flight_6E-153  \
0          False          False          False          False          False   
1          False          False          False          False          False   
2          False          False          False          False          False   
3          False          False          False          False          False   
4          False          False          False          False          False   

   flight_6E-154  flight_6E-156  flight_6E-157  flight_6E-161  flight_6E-164  \
0          False          False          False          False          False   
1          False          False          False          False          False   
2          False          False          False          False          False   
3          False          False          False          False          False   
4          False          False          False          False          False   

   flight_6E-165  flight_6E-168  flight_6E-171  flight_6E-172  flight_6E-176  \
0          False          False          False          False          False   
1          False          False          False          False          False   
2          False          False          False          False          False   
3          False          False          False          False          False   
4          False          False          False          False          False   

   flight_6E-177  flight_6E-179  flight_6E-181  flight_6E-183  flight_6E-184  \
0          False          False          False          False          False   
1          False          False          False          False          False   
2          False 

### 사이킷런으로 원핫 인코딩하기 - OneHotEncoder 클래스

In [102]:
df = df_origin.copy()


oh = OneHotEncoder()
# fit_transform()에는 2차원 배열이 들어가야 한다.
df['class'].values

<ArrowStringArray>
[ 'Economy',  'Economy',  'Economy',  'Economy',  'Economy',  'Economy',
  'Economy',  'Economy',  'Economy',  'Economy',
 ...
 'Business', 'Business', 'Business', 'Business', 'Business', 'Business',
 'Business', 'Business', 'Business', 'Business']
Length: 300153, dtype: str

In [103]:
df['class'].values.reshape(-1, 1)

NotImplementedError: <class 'pandas.arrays.ArrowStringArray'> does not support reshape as backed by a 1D pyarrow.ChunkedArray.

In [ ]:
oh.fit_transform(df['class'].values.reshape(-1,1)).toarray()

NotImplementedError: <class 'pandas.arrays.ArrowStringArray'> does not support reshape as backed by a 1D pyarrow.ChunkedArray.

- onHotEncoder는 배열을 반환(array)
- 왜 바로 데이터프레임에 반영되지 않는가?
    - 머신러닝 파이프라인에 바로 연결해서 train/test 데이터에 동일한 인코딩 규칙을 일관되게 적용하기 위해 설계된 도구이기 때문
    - 단순 EDA/전처리용으로는 get_dummies가 훨씬 간편하다.
    - 실제 머신러닝 모델링에서는 OneHotEncoder를 사용하는 경우도 많다.