## 로지스틱 회귀
- 0~1 사이의 확률을 출력하고, 이를 임계값으로 잘라서 참(1)/거짓(0)으로 분류한다.

In [4]:
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

DATA_DIR = Path('ml_실습데이터')
if not DATA_DIR.exists():
    DATA_DIR = Path('ml_실습데이터')
print(f'데이터 폴더 : {DATA_DIR.resolve()}')

데이터 폴더 : C:\Users\Administrator\bigdata2026\data_analysis\ml_실습데이터


### 라이브러리 불러오기

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression  # 로지스틱 회귀 분류 모델
from sklearn.impute import SimpleImputer # 결측치를 특정 값으로 채워주는 전처리 클래스
from sklearn.pipeline import make_pipeline  # 여러 전처리 단계와 모델을 하나로 연결해주는 도구
from sklearn.metrics import confusion_matrix, classification_report # 분류 성능을 평가하는 지표함수들

In [6]:
df = pd.read_csv(DATA_DIR / 'telecom_churn.csv') # 통신사 고객 이탈 데이터 불러오기
df.head()

,usage_minutes,complaints,contract_months,monthly_fee,contract_type,region,churn
0,321.0,2,12,63.6,one-year,Gyeonggi,1
1,80.0,1,6,62.2,two-year,Gyeonggi,1
2,251.0,1,31,71.6,month-to-month,Other,0
3,158.0,0,31,58.8,two-year,Seoul,0
4,356.0,1,32,58.9,one-year,Gyeonggi,0


In [7]:
# 예측에 사용할 입력 변수(특성/feature) 4개를 선정
features = ['usage_minutes', 'complaints', 'contract_months', 'monthly_fee']

X = df[features]
y = df['churn']

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.25, stratify=y, random_state=42
)

X_train.shape, X_valid.shape, y_train.shape, y_valid.shape

((315, 4), (105, 4), (315,), (105,))

In [12]:
model = make_pipeline(
    SimpleImputer(strategy='median'),   # 결측치를 중앙값으로 대체 (평균보다 이상치에 덜 민감)
    LogisticRegression(max_iter=1000)   # 반복 횟수를 늘려 실패 경고 방지
)
model.fit(X_train, y_train) # 학습

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators ` for more details.","[('simpleimputer', ...), ('logisticregression', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing `.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"missing_values missing_values: int, float, str, np.nan, None or pandas.NA, default=np.nanThe placeholder for the missing values. All occurrences of`missing_values` will be imputed. For pandas' dataframes withnullable integer dtypes with missing values, `missing_values`can be set to either `np.nan` or `pd.NA`.",nan
,"strategy strategy: str or Callable, default='mean'The imputation strategy.- If ""mean"", then replace missing values using the mean along each column. Can only be used with numeric data.- If ""median"", then replace missing values using the median along each column. Can only be used with numeric data.- If ""most_frequent"", then replace missing using the most frequent value along each column. Can be used with strings or numeric data. If there is more than one such value, only the smallest is returned.- If ""constant"", then replace missing values with fill_value. Can be used with strings or numeric data.- If an instance of Callable, then replace missing values using the scalar statistic returned by running the callable over a dense 1d array containing non-missing values of each column... versionadded:: 0.20 strategy=""constant"" for fixed value imputation... versionadded:: 1.5 strategy=callable for custom value imputation.",'median'
,"fill_value fill_value: str or numerical value, default=NoneWhen strategy == ""constant"", `fill_value` is used to replace alloccurrences of missing_values. For string or object data types,`fill_value` must be a string.If `None`, `fill_value` will be 0 when imputing numericaldata and ""missing_value"" for strings or object data types.",None
,"copy copy: bool, default=TrueIf True, a copy of X will be created. If False, imputation willbe done in-place whenever possible. Note that, in the following cases,a new copy will always be made, even if `copy=False`:- If `X` is not an array of floating values;- If `X` is encoded as a CSR matrix;- If `add_indicator=True`.",True
,"add_indicator add_indicator: bool, default=FalseIf True, a :class:`MissingIndicator` transform will stack onto outputof the imputer's transform. This allows a predictive estimatorto account for missingness despite 

In [13]:
model.predict_proba(X_valid)

array([[0.50515355, 0.49484645],
       [0.67955963, 0.32044037],
       [0.64657635, 0.35342365],
       [0.62144523, 0.37855477],
       [0.41023464, 0.58976536],
       [0.86088348, 0.13911652],
       [0.65234881, 0.34765119],
       [0.70563235, 0.29436765],
       [0.75437264, 0.24562736],
       [0.47447862, 0.52552138],
       [0.8916972 , 0.1083028 ],
       [0.52789702, 0.47210298],
       [0.87735934, 0.12264066],
       [0.72409078, 0.27590922],
       [0.45715944, 0.54284056],
       [0.69615509, 0.30384491],
       [0.34322511, 0.65677489],
       [0.83302227, 0.16697773],
       [0.80431175, 0.19568825],
       [0.88728521, 0.11271479],
       [0.53709419, 0.46290581],
       [0.26167395, 0.73832605],
       [0.73099461, 0.26900539],
       [0.48643864, 0.51356136],
       [0.40674106, 0.59325894],
       [0.33160343, 0.66839657],
       [0.74091379, 0.25908621],
       [0.82111806, 0.17888194],
       [0.53026172, 0.46973828],
       [0.8203046 , 0.1796954 ],
       [0.

In [15]:
proba = model.predict_proba(X_valid)[:, 1]   # [비이탈확률, 이탈확률] 두 열을 반환 --> 이탈(1) 확률 알기

# 임계값(threshold) 0.5
pred = (proba >= 0.5).astype(int)  # 0.5이상인 것만 추려서 정수형으로 형 변환
pred

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0])

### 혼동행렬 (confusion_matrix)

[[TN, FP],

 [FN, TP]]

- TP : 실제 이탈을 이탈로 정확히 맞췄다
- TN : 실제 비이탈을 비이탈로 정확히 맞췄다
- FP : 실제 비이탈을 이탈로 잘못 예측
- FN : 실제 이탈을 비이탈로 잘못 예측

In [16]:
print(confusion_matrix(y_valid, pred))

[[58 12]
 [22 13]]


In [ ]:
print(classification_report(y_valid, pred, digits=3)) # 소수 3째자리까지 
# 정밀도, 재현율, 조화평균, 클래스별 표본 수

              precision    recall  f1-score   support

           0      0.725     0.829     0.773        70
           1      0.520     0.371     0.433        35

    accuracy                          0.676       105
   macro avg      0.623     0.600     0.603       105
weighted avg      0.657     0.676     0.660       105



### 예측 결과를 실제 데이터프레임 형태로 확인

In [18]:
sample = X_valid.head().copy()  
sample

,usage_minutes,complaints,contract_months,monthly_fee
162,379.0,1,2,78.8
358,176.0,1,23,69.5
177,341.0,1,4,38.9
391,264.0,2,25,51.3
52,387.0,2,11,82.8


In [19]:
y_valid.head()

162    1
358    0
177    0
391    0
52     1
Name: churn, dtype: int64

In [21]:
sample['actual'] = y_valid.head()  # 실제 정답(이탈 여부) 열 추가
sample['churn_probability'] = proba[:5]  # 모델이 계산한 이탈 확률 열 추가
sample

,usage_minutes,complaints,contract_months,monthly_fee,actual,churn_probability
162,379.0,1,2,78.8,1,0.494846
358,176.0,1,23,69.5,0,0.320440
177,341.0,1,4,38.9,0,0.353424
391,264.0,2,25,51.3,0,0.378555
52,387.0,2,11,82.8,1,0.589765


## 정답 없이 비슷한 데이터를 묶는 군집화
- 비지도 학습

### k-means clustering (k-평균 군집화)
- 중심점을 무작위로 놓는다 -> 가까운 점들을 그 중심에 배정 -> 배정된 점들의 평균으로 중심을 다시 계산
- 위의 과정을 계속해서 반복한다.

In [22]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples # 군집이 얼마나 잘 분리되어 있나를 -1 ~ 1값으로 나타낸다.
# 1에 가까울수록 좋다.

In [23]:
df = pd.read_csv(DATA_DIR / 'customer_segments.csv')
df.head()

,customer_id,annual_spend_10k,visits_per_month,online_ratio
0,C0001,52.0,5.0,0.69
1,C0002,147.6,16.2,0.08
2,C0003,34.1,4.6,0.69
3,C0004,81.6,12.4,0.57
4,C0005,119.2,7.8,0.38


In [24]:
features = ['annual_spend_10k', 'visits_per_month', 'online_ratio']

# 표준화 스케일링이 필요한 이유 : 거리 기반 알고리즘(k-means)이므로 변수 간 스케일(단위)이 다르면 왜곡된다.
X_scaled = StandardScaler().fit_transform(df[features])

X_scaled

array([[-8.19440716e-01, -1.09146291e+00,  8.34049339e-01],
       [ 1.08824013e+00,  8.52371299e-01, -1.71643240e+00],
       [-1.17663200e+00, -1.16088556e+00,  8.34049339e-01],
       [-2.28778027e-01,  1.92856122e-01,  3.32315227e-01],
       [ 5.21523227e-01, -6.05504355e-01, -4.62097117e-01],
       [-8.75314214e-01, -9.17906281e-01,  1.41940580e+00],
       [-1.29636093e+00, -9.35261943e-01,  1.58665051e+00],
       [ 1.02837567e+00,  1.58130913e+00, -9.63831229e-01],
       [-1.98845796e-01,  7.13664844e-02,  4.15937579e-01],
       [ 8.38804874e-01,  5.05258048e-01, -1.63281004e+00],
       [ 7.23066915e-01,  9.04438286e-01, -8.57965331e-02],
       [-8.90942830e-02, -8.48344785e-02,  7.08615811e-01],
       [ 1.07626724e+00,  9.56505274e-01, -9.63831229e-01],
       [-6.59802152e-01,  2.44923110e-01, -2.11230061e-01],
       [ 1.09422658e+00,  2.36231394e+00, -1.17288711e+00],
       [ 2.36169293e-01,  3.66551593e-02, -2.11230061e-01],
       [-1.17264104e+00, -9.17906281e-01

In [31]:
results = []
for k in range(2, 6):  # k=2,3,4,5
    # n_clusters : 몇 개의 그룹(군집)으로 나눌지 정한다. 2,3,4,5 --> 우리가 지정해야 한다. 
    # n_init : 서로 다른 초기 중심점으로 10번 반복 실행 후 가장 좋은 결과를 선택(초기값에 따른 편차 완화)
    labels = KMeans(n_clusters=k, n_init=10, random_state=42).fit_predict(X_scaled)
    results.append({
        'k': k,
        'silhouette': silhouette_samples(X_scaled, labels)
    }) # k값에 따른 실루엣 점수를 비교해서 군집이 잘 나뉘는 k를 찾는 것이 목표
results

[{'k': 2,
  'silhouette': array([0.67805705, 0.66618692, 0.6782137 , 0.42807667, 0.15472003,
         0.668023  , 0.65057006, 0.70694186, 0.47058909, 0.58742667,
         0.3837033 , 0.51038164, 0.6993368 , 0.34844433, 0.62909388,
         0.15938064, 0.66105471, 0.21219561, 0.58817448, 0.66008577,
         0.68618713, 0.44472437, 0.65556352, 0.51414485, 0.448809  ,
         0.7261143 , 0.52312937, 0.39015123, 0.40916692, 0.39925613,
         0.68738008, 0.71199378, 0.12789777, 0.64256407, 0.64501849,
         0.69262985, 0.42708664, 0.72016207, 0.65773335, 0.64403698,
         0.43026131, 0.65306991, 0.05292601, 0.67147088, 0.66867074,
         0.67575665, 0.74020311, 0.68821988, 0.33945011, 0.0953472 ,
         0.19151075, 0.42842014, 0.10440691, 0.50810164, 0.68535844,
         0.72294863, 0.58542038, 0.63731596, 0.68665326, 0.38290721,
         0.20003061, 0.63132209, 0.64687123, 0.63964375, 0.33652745,
         0.65874151, 0.69097612, 0.67071143, 0.65907413, 0.60447245,
         0

In [32]:
silhouette_samples(X_scaled, labels)

array([ 0.57773981,  0.28609247,  0.68197011,  0.47942641,  0.37365637,
        0.66274865,  0.6996323 ,  0.30500388,  0.48607481,  0.39014784,
        0.05713367,  0.46744149,  0.31756727,  0.10308035,  0.44354696,
        0.14366014,  0.50942689,  0.13773565,  0.4655662 ,  0.7350225 ,
        0.74638746,  0.32014362,  0.69859558,  0.05755587,  0.14252028,
        0.41034809,  0.04996438,  0.33652001,  0.08119334,  0.17844466,
        0.34765327,  0.50723967,  0.36457331,  0.09428176,  0.68350696,
        0.35298217,  0.37331822,  0.47424107,  0.59453962,  0.61976427,
        0.502381  ,  0.7234324 ,  0.27805576,  0.69360956,  0.30861184,
        0.61012091, -0.04727741,  0.71474814,  0.39786292, -0.00222002,
        0.11393043,  0.34771651,  0.09722634,  0.046452  ,  0.63433102,
        0.16059471,  0.40048776,  0.65464013,  0.36363053,  0.41181943,
        0.17273074,  0.67058448,  0.69791363,  0.39381098,  0.42590674,
        0.15703547,  0.72787058,  0.65364449,  0.32108897,  0.63

In [33]:
pd.DataFrame(results)

,k,silhouette
0,2,"[0.6780570548614363, 0.6661869240477926, 0.678..."
1,3,"[0.6211828176866513, 0.5427601005046613, 0.706..."
2,4,"[0.5964290540868225, 0.5097940666848703, 0.693..."
3,5,"[0.5777398084901512, 0.286092465149842, 0.6819..."


### k=3으로 최종 군집화하고, 각 군집의 특징을 평균값으로 요약(프로파일링)

In [34]:
model = KMeans(n_clusters=3, n_init=10, random_state=42)
df.head()

,customer_id,annual_spend_10k,visits_per_month,online_ratio
0,C0001,52.0,5.0,0.69
1,C0002,147.6,16.2,0.08
2,C0003,34.1,4.6,0.69
3,C0004,81.6,12.4,0.57
4,C0005,119.2,7.8,0.38


In [36]:
df['cluster'] = model.fit_predict(X_scaled)  # 원본 df에 군집 번호 열 추가
df.head(10)

,customer_id,annual_spend_10k,visits_per_month,online_ratio,cluster
0,C0001,52.0,5.0,0.69,0
1,C0002,147.6,16.2,0.08,1
2,C0003,34.1,4.6,0.69,0
3,C0004,81.6,12.4,0.57,2
4,C0005,119.2,7.8,0.38,2
5,C0006,49.2,6.0,0.83,0
6,C0007,28.1,5.9,0.87,0
7,C0008,144.6,20.4,0.26,1
8,C0009,83.1,11.7,0.59,2
9,C0010,135.1,14.2,0.10,1


In [37]:
profile = df.groupby('cluster')[features].mean().round(2)

In [38]:
profile

,annual_spend_10k,visits_per_month,online_ratio
cluster,,,
0,36.31,5.24,0.77
1,156.68,18.41,0.23
2,91.81,10.88,0.46


In [ ]:
# 각 군집에 몇 명이 속하는지 표본 수 확인
profile['count'] = df['cluster'].value_counts().sort_index()
profile

,annual_spend_10k,visits_per_month,online_ratio,count
cluster,,,,
0,36.31,5.24,0.77,82
1,156.68,18.41,0.23,75
2,91.81,10.88,0.46,93


In [40]:
# 각 군집(cluster)의 평균 프로필을 보고 행동 중심으로 이름 붙이기 예시
names = {
    0: '온라인 중심 저빈도 고객: 연간 구매액과 방문 횟수는 낮지만 온라인 구매 비율이 높다.',
    1: '매장 중심 우수 고객: 연간 구매액과 방문 횟수가 가장 높고 온라인 비율은 낮다.',
    2: '균형형 일반 고객: 구매액과 방문 횟수, 온라인 비율이 모두 중간 수준이다.'
}
df['cluster_name'] = df['cluster'].map(names) # 숫자 군집 번호를 사람이 읽을 수 있는 이름으로 매핑
df.head(10)

,customer_id,annual_spend_10k,visits_per_month,online_ratio,cluster,cluster_name
0,C0001,52.0,5.0,0.69,0,온라인 중심 저빈도 고객: 연간 구매액과 방문 횟수는 낮지만 온라인 구매 비율이 높다.
1,C0002,147.6,16.2,0.08,1,매장 중심 우수 고객: 연간 구매액과 방문 횟수가 가장 높고 온라인 비율은 낮다.
2,C0003,34.1,4.6,0.69,0,온라인 중심 저빈도 고객: 연간 구매액과 방문 횟수는 낮지만 온라인 구매 비율이 높다.
3,C0004,81.6,12.4,0.57,2,"균형형 일반 고객: 구매액과 방문 횟수, 온라인 비율이 모두 중간 수준이다."
4,C0005,119.2,7.8,0.38,2,"균형형 일반 고객: 구매액과 방문 횟수, 온라인 비율이 모두 중간 수준이다."
5,C0006,49.2,6.0,0.83,0,온라인 중심 저빈도 고객: 연간 구매액과 방문 횟수는 낮지만 온라인 구매 비율이 높다.
6,C0007,28.1,5.9,0.87,0,온라인 중심 저빈도 고객: 연간 구매액과 방문 횟수는 낮지만 온라인 구매 비율이 높다.
7,C0008,144.6,20.4,0.26,1,매장 중심 우수 고객: 연간 구매액과 방문 횟수가 가장 높고 온라인 비율은 낮다.
8,C0009,83.1,11.7,0.59,2,"균형형 일반 고객: 구매액과 방문 횟수, 온라인 비율이 모두 중간 수준이다."
9,C0010,135.1,14.2,0.10,1,매장 중심 우수 고객: 연간 구매액과 방문 횟수가 가장 높고 온라인 비율은 낮다.
